// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.web;

import com.sut.test.domain.Sample;
import com.sut.test.web.SampleController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect SampleController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String SampleController.create(@Valid Sample sample, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, sample);
            return "samples/create";
        }
        uiModel.asMap().clear();
        sample.persist();
        return "redirect:/samples/" + encodeUrlPathSegment(sample.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String SampleController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Sample());
        return "samples/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String SampleController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("sample", Sample.findSample(id));
        uiModel.addAttribute("itemId", id);
        return "samples/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String SampleController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("samples", Sample.findSampleEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Sample.countSamples() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("samples", Sample.findAllSamples(sortFieldName, sortOrder));
        }
        return "samples/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String SampleController.update(@Valid Sample sample, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, sample);
            return "samples/update";
        }
        uiModel.asMap().clear();
        sample.merge();
        return "redirect:/samples/" + encodeUrlPathSegment(sample.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String SampleController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Sample.findSample(id));
        return "samples/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String SampleController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Sample sample = Sample.findSample(id);
        sample.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/samples";
    }
    
    void SampleController.populateEditForm(Model uiModel, Sample sample) {
        uiModel.addAttribute("sample", sample);
    }
    
    String SampleController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
